services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 33061:3306
    hostname: mariadb.local
    volumes:
      - ./mariadb:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - transfashion
    environment:
      MYSQL_ROOT_PASSWORD: ieMWilI0jhJiPJDWKsDqx2jgrCrxqw
      TERM: xterm-256color
networks:
  transfashion:
    name: transfashion
    external: true
